# Aiven MySQL 接続設定
spring.datasource.url=jdbc:mysql://mysql-98fce2f-youshengguangen563-7c39.a.aivencloud.com:13773/defaultdb?ssl-mode=REQUIRED&useSSL=true
spring.datasource.username=avnadmin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=${DB_PASSWORD}
# Hibernateの設定（テーブルを自動作成させる）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
