spring.datasource.url=jdbc:mysql://mysql-98fce2f-youshengguangen563-7c39.a.aivencloud.com:13773/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
server.port=${PORT:10000}
